#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * Native Gameplay Tags owned by DocModularCore.
 *
 * Only tags genuinely shared by several features live here: error categories used
 * in FDocSystemResult and control capabilities used by IDocPlayerControlProvider.
 * Feature roots (Interaction.*, Event.*, Region.*, ...) are registered by their
 * owning feature plugins, never by Core.
 *
 * Public tag names are part of the API. Do not rename after content or saves ship;
 * add a redirect in project config instead.
 */
namespace DocCoreTags
{
	// Error categories (extensible: features add children such as Doc.Error.Interaction.OutOfRange).
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Unset);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Unsupported);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_NotReady);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_NotFound);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_InvalidConfiguration);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_PermissionDenied);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Cancelled);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_TimedOut);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_ExecutionFailed);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_InvalidInput);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Unavailable);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Conflict);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Storage);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Handle_Invalid);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Handle_Stale);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Handle_WrongScope);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Identity_Invalid);

	// Local-player control capabilities (IDocPlayerControlProvider).
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Camera);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Input);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Input_Movement);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Input_Look);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Pause);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_HUD);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Cursor);
	DOCMODULARCORERUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Control_Focus);
}
